### ISSUE TITLE
Failing with TypeError: string indices must be integers

### ISSUE THREAD

**Issue by routerworld3** [nickrusso42518/narc#27]
I run this in the Windows & my Linux box with virtual Enviornment & I get the same result.
I do see ssh connection to the ASA so I know that part may be working but not sure how to troubleshoot .
Do you start from the top where error gives or bottom.

```
ASA version is 9.1(5)16
(narc) lab@lab-vm:~/narc$ python -V
Python 3.6.9

E:\Python\00_Nick_Russo\narc-master>python3 -i runbook.py --status
ASAV1@2020-09-02T15:29:13.228952: loading YAML vars
ASAV1@2020-09-02T15:29:13.243908: loading vars succeeded
ASAV1@2020-09-02T15:29:13.243908: starting  check DNS OUTBOUND (1/5)
ASAV1@2020-09-02T15:29:21.357049: completed check DNS OUTBOUND (1/5)
ASAV1@2020-09-02T15:29:21.357049: starting  check HTTPS OUTBOUND (2/5)
ASAV1@2020-09-02T15:29:22.262786: completed check HTTPS OUTBOUND (2/5)
ASAV1@2020-09-02T15:29:22.262786: starting  check SSH INBOUND (3/5)
ASAV1@2020-09-02T15:29:23.268578: completed check SSH INBOUND (3/5)
ASAV1@2020-09-02T15:29:23.268578: starting  check PING OUTBOUND (4/5)
ASAV1@2020-09-02T15:29:24.274980: completed check PING OUTBOUND (4/5)
ASAV1@2020-09-02T15:29:24.275932: starting  check L2TP OUTBOUND (5/5)
ASAV1@2020-09-02T15:29:25.484300: completed check L2TP OUTBOUND (5/5)
Traceback (most recent call last):
  File "runbook.py", line 68, in <module>
    main(_process_args())
  File "runbook.py", line 25, in main
    aresult = nornir.run(task=run_checks, args=args)
  File "C:\Users\vpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\nornir\core\__init__.py", li
ne 155, in run
    result = self._run_parallel(task, run_on, num_workers, **kwargs)
  File "C:\Users\vpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\nornir\core\__init__.py", li
ne 93, in _run_parallel
    worker_result = future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\vpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\nornir\core\task.py", line 1
17, in start
    self.nornir.processors.task_instance_completed(self, host, self.results)
  File "C:\Users\vpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\nornir\core\processor.py", l
ine 85, in task_instance_completed
    p.task_instance_completed(task, host, result)
  File "E:\Python\00_Nick_Russo\narc-master\narc\processors\proc_terse.py", line 50, in task_instance_completed
    action = data["root"]["result"]["action"]
TypeError: string indices must be integers
```

**Comment by nickrusso42518** [comment]
Please supply the output for `pip show`.

Also within the `narc\processors\proc_terse.py` file, please add the following line of code right after `action = data["root"]["result"]["action"]` on line 50:

`import json; print(json.dumps(data,indent=2))`

Then show me the output from that.

**Comment by routerworld3** [comment]
Thank you Nick , found the issue there was no managment interface so it failed as invalid input detected.
After changing the input interface to inside it worked fine. I feel guilty about my stupidity.
I learn something I could have just put the print statement from the error in correct file ( proc-terse.py) 
I knew about the print statement but was not sure about the proc_terse.py location but looking at the error I see now.
```
 {
  "root": "packet-tracer input management tcp fc00:172:31:1::a 5000 fc00:192:0:2::2$ent tcp fc00:172:31:1::a 5000 fc00:192:0:2::2                          22 xmlpacket-tracer
 input management tcp fc00:172:31:1::a 5000 fc00:192:0:2::$\n\npacket-tracer input management tcp fc00:172:31:1::a 5000 fc00:192:0:2::2 22 xml\n                    ^\nERROR:
% Invalid input detected at '^' marker."
}
Traceback (most recent
```
Sincerley
Viral Patel
