### ISSUE TITLE
error with string indices that should be integer

### ISSUE THREAD

**Issue by novolyus** [nickrusso42518/narc#28]
Hi Nick, I suffer from this issue when I run the script:

```
(narc) [franquezaj narc]$ python runbook.py --status
ASAV1@2021-01-25T13:55:00.854568: loading YAML vars
ASAV1@2021-01-25T13:55:00.859045: loading vars succeeded
ASAV1@2021-01-25T13:55:00.859180: starting  check DNS OUTBOUND (1/1)
ASAV1@2021-01-25T13:55:06.167691: completed check DNS OUTBOUND (1/1)
Traceback (most recent call last):
  File "runbook.py", line 68, in <module>
    main(_process_args())
  File "runbook.py", line 25, in main
    aresult = nornir.run(task=run_checks, args=args)
  File "/home/dpko.un.org/franquezaj-su/narc/lib64/python3.6/site-packages/nornir/core/__init__.py", line 148, in run
    result = self._run_parallel(task, run_on, num_workers, **kwargs)
  File "/home/dpko.un.org/franquezaj-su/narc/lib64/python3.6/site-packages/nornir/core/__init__.py", line 86, in _run_parallel
    r = rp.get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/dpko.un.org/franquezaj-su/narc/lib64/python3.6/site-packages/nornir/core/task.py", line 117, in start
    self.nornir.processors.task_instance_completed(self, host, self.results)
  File "/home/dpko.un.org/franquezaj-su/narc/lib64/python3.6/site-packages/nornir/core/processor.py", line 85, in task_instance_completed
    p.task_instance_completed(task, host, result)
  File "/home/reponeg/nexus/franquezaj/PYTHON/russo/narc/narc/processors/proc_csv.py", line 53, in task_instance_completed
    action = data["root"]["result"]["action"]
TypeError: string indices must be integers
```

**Comment by nickrusso42518** [comment]
I'm assuming that `action = data["root"]["result"]` is a string instead of a dictionary. Please try the runbook again using only the JSON processor. Edit the code like so:

`nornir = init_nornir.with_processors([ProcJSON()])`

Then, post the output from the `result.json` file. Additionally, please let me know which version of Cisco ASA you are running and which version of Nornir you have installed.

**Comment by novolyus** [comment]
The issue is related with the FW context configuration and not the code.
